双十一淘宝美妆数据.csv 这个数据集是美妆店铺的双十一销售数据，可以挖掘的纬度有日期、店铺，指标则有销售量、销售额、评论数等。

# 1、数据理解与处理

In [1]:
#!pip install chardet  
import pandas as pd
import chardet

# 检测文件编码（核心代码）
file_path = r'..\data\双十一淘宝美妆数据.csv'

# 读取文件二进制内容（用rb)
with open(file_path, 'rb') as f:
    # 读取前10000字节（足够检测编码，不用读整个文件）
    raw_data = f.read(10000)
    # 检测编码，返回最大概率结果
    detect_result = chardet.detect(raw_data)

# 输出检测结果
print("=== 编码检测结果 ===")
print(f"最大概率编码：{detect_result['encoding']}")
print(f"可信度（0-1）：{detect_result['confidence']:.2f}")

=== 编码检测结果 ===
最大概率编码：UTF-8-SIG
可信度（0-1）：1.00

In [2]:
import pandas as pd
data2 = pd.read_csv(r'..\data\双十一淘宝美妆数据.csv',engine = 'python',encoding = 'UTF-8-SIG', header=0)#用python读，读完乱码就设置编码，上面读出来什么就用什么
data2.head()

,update_time,id,title,price,sale_count,comment_count,店名
0,2016/11/14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂
1,2016/11/14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂
2,2016/11/14,A18177226992,CHANDO/自然堂活泉保湿修护精华水（滋润型135ml 补水控油爽肤水,99.0,12668.0,589.0,自然堂
3,2016/11/14,A18178033846,CHANDO/自然堂 男士劲爽控油洁面膏 100g 深层清洁 男士洗面奶,38.0,25805.0,4287.0,自然堂
4,2016/11/14,A18178045259,CHANDO/自然堂雪域精粹纯粹滋润霜（清爽型）50g补水保湿滋润霜,139.0,5196.0,618.0,自然堂

In [3]:
data2.info()  # 数据集情况 27597 条，7个字段

<class 'pandas.DataFrame'>
RangeIndex: 27598 entries, 0 to 27597
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   update_time    27598 non-null  str
 1   id             27598 non-null  str
 2   title          27598 non-null  str
 3   price          27598 non-null  float64
 4   sale_count     25244 non-null  float64
 5   comment_count  25244 non-null  float64
 6   店名             27598 non-null  str
dtypes: float64(3), str(4)
memory usage: 1.5 MB

In [4]:
data2[data2.duplicated()].count() # 有86条完全重复数据

update_time      86
id               86
title            86
price            86
sale_count       82
comment_count    82
店名               86
dtype: int64

In [5]:
data2.drop_duplicates(inplace=True)   # 删除重复数据
data2.reset_index(drop=True, inplace=True)  # 重建索引
data2.isnull().sum()  # 查看空值 ，销售数量和评论数有空值

update_time         0
id                  0
title               0
price               0
sale_count       2350
comment_count    2350
店名                  0
dtype: int64

In [6]:
data2.fillna(0, inplace=True) # 空值填充
data2['update_time'] = pd.to_datetime(data2['update_time']).apply(lambda x: x.strftime("%Y-%m-%d")) # 日期格式化，便于统计

In [7]:
data2[data2['sale_count']>0].sort_values(by=['sale_count']).head() # 从数据来看，sale_count 是销售量

,update_time,id,title,price,sale_count,comment_count,店名
24566,2016-11-06,A540035616409,【娇兰预售】娇兰水合青春保湿BB霜40ml明亮色 裸妆遮瑕持久,620.0,1.0,0.0,娇兰
21769,2016-11-09,A540804667599,【11.11专享】兰芝水衡水乳面膜精华套装 补水保湿 滋润 官方正品,920.0,1.0,0.0,兰芝
21764,2016-11-09,A540798153439,【11.11专享】水衡水乳+唇膜面膜套装 补水保湿 滋润,750.0,1.0,0.0,兰芝
21883,2016-11-08,A540068751642,【11.11专享】兰芝新水酷特润精华+眼部ㄠ 礼盒 补水保湿,565.0,1.0,0.0,兰芝
21757,2016-11-09,A540068751642,【11.11专享】兰芝新水酷特润精华+眼部ㄠ 礼盒 补水保湿,565.0,1.0,0.0,兰芝

In [8]:
data2['sale_amount'] = data2['price'] * data2['sale_count']  # 增加一列销售额
data2[data2['sale_count']>0].sort_values(by=['sale_amount']) # 销售额从低到高

,update_time,id,title,price,sale_count,comment_count,店名,sale_amount
27042,2016-11-05,A541190557158,Herborist/佰草集新美肌梦幻曲面贴膜3片 保湿补水,1.0,1.0,0.0,佰草集,1.0
26273,2016-11-08,A541190557158,Herborist/佰草集新美肌梦幻曲面贴膜3片 保湿补水,1.0,1.0,0.0,佰草集,1.0
26785,2016-11-06,A541190557158,Herborist/佰草集新美肌梦幻曲面贴膜3片 保湿补水,1.0,1.0,0.0,佰草集,1.0
26530,2016-11-07,A541190557158,Herborist/佰草集新美肌梦幻曲面贴膜3片 保湿补水,1.0,1.0,0.0,佰草集,1.0
25761,2016-11-10,A541190557158,Herborist/佰草集新美肌梦幻曲面贴膜3片 保湿补水,1.0,2.0,0.0,佰草集,2.0
...,...,...,...,...,...,...,...,...
10439,2016-11-09,A13956982789,【双11来啦】相宜本草红石榴护肤化妆品套装女美白补水乳保湿,218.0,433603.0,9823.0,相宜本草,94525454.0
10306,2016-11-10,A13956982789,【双11来啦】相宜本草红石榴护肤化妆品套装女美白补水乳保湿,218.0,433604.0,9712.0,相宜本草,94525672.0
10027,2016-11-13,A13956982789,相宜本草红石榴护肤化妆品套装女美白补水乳保湿,218.0,444263.0,9427.0,相宜本草,96849334.0
9940,2016-11-14,A13956982789,相宜本草红石榴护肤化妆品套装女美白补水乳保湿,218.0,444271.0,9355.0,相宜本草,96851078.0
10117,2016-11-12,A13956982789,相宜本草红石榴护肤化妆品套装女美白补水乳保湿,218.0,444337.0,9509.0,相宜本草,96865466.0

# 2、数据分析与可视化

2.1 每日整体销售量走势

In [9]:
from pyecharts import options as opts
from pyecharts.charts import Line

result = data2.groupby('update_time').agg({'sale_count':'sum'}).to_dict()['sale_count']
c = (
    Line()
    .add_xaxis(list(result.keys()))
    .add_yaxis("销售量", list(result.values()))
    .set_series_opts(
        areastyle_opts=opts.AreaStyleOpts(opacity=0.5),
        label_opts=opts.LabelOpts(is_show=False),
        markpoint_opts=opts.MarkPointOpts(
            data=[
                opts.MarkPointItem(type_="max", name="最大值"),
                opts.MarkPointItem(type_="min", name="最小值"),
                opts.MarkPointItem(type_="average", name="平均值"),
            ]
        ),
    )
    .set_global_opts(title_opts=opts.TitleOpts(title="每日整体销售量走势"))
)
c.render_notebook()

2.2 谁家的化妆品卖的最好

In [10]:
dts = list(data2['update_time'].unique())
dts.reverse()
dts

['2016-11-05',
 '2016-11-06',
 '2016-11-07',
 '2016-11-08',
 '2016-11-09',
 '2016-11-10',
 '2016-11-11',
 '2016-11-12',
 '2016-11-13',
 '2016-11-14']

In [11]:
from pyecharts import options as opts
from pyecharts.charts import Map, Timeline, Bar, Line, Pie
from pyecharts.components import Table
from pyecharts.options import ComponentTitleOpts

tl = Timeline()
tl.add_schema(
#         is_auto_play=True,#动态播放，下面那个play_interval是播放间隔，这里没用，需要可以打开
        is_loop_play=False,
        play_interval=500,
    )
for dt in dts:
    #截止在dt时间前的销售量排序
    item = data2[data2['update_time'] <= dt].groupby('店名').agg({'sale_count': 'sum', 'sale_amount': 'sum'}).sort_values(by='sale_count', ascending=False)[:10].sort_values(by='sale_count').to_dict()
    bar = (
        Bar()
        .add_xaxis([*item['sale_count'].keys()])
        .add_yaxis("销售量", [round(val/10000,2) for val in item['sale_count'].values()], label_opts=opts.LabelOpts(position="right", formatter='{@[1]/} 万'))
        .add_yaxis("销售额", [round(val/10000/100,2) for val in item['sale_amount'].values()], label_opts=opts.LabelOpts(position="right", formatter='{@[1]/} 百万元'))
        .reversal_axis()
        .set_global_opts(
            title_opts=opts.TitleOpts("累计销售量排行 TOP10")
        )
    )
    tl.add(bar, dt)
tl.render_notebook()

In [12]:
item = data2.groupby('店名').agg({'sale_count': 'sum'}).sort_values(by='sale_count', ascending=False)[:10].to_dict()['sale_count']
item = {k: round(v/10000, 2) for k, v in item.items()}
c = (
    Pie()
    .add("销量", [*item.items()])
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c} 万({d}%)"))
)
c.render_notebook()

2.3 谁家的化妆品最贵

In [13]:
item = data2.groupby('店名').agg({'price': 'mean'}).sort_values(by='price', ascending=False)[:20].sort_values(by='price').to_dict()
c = (
    Bar()
    .add_xaxis([*item['price'].keys()])
    .add_yaxis("平均价格", [round(v, 2) for v in item['price'].values()], label_opts=opts.LabelOpts(position="right"))
    .reversal_axis()
    .set_global_opts(
        title_opts=opts.TitleOpts("平均价格排行 TOP20")
    )
)
c.render_notebook()